# action.yml
name: 'Release-Notes'
description: 'The action for publishing release notes'
inputs:
  github-token:  
    description: 'A GitHub personal access token used to commit to a branch on your behalf.'
    required: true
  branch:  
    description: 'The branch'
    required: false
    default: 'main'
  org:  
    description: 'Github Organization Name'
    required: false
  user:  
    description: 'Github User Name'
    required: false
runs:
  using: 'docker'
  image: 'docker://dlahuta/github.release.notes:35a3728-unsupported'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.branch }}
    - ${{ inputs.org }}
    - ${{ inputs.user }}
