// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/infobloxopen/atlas-cli/github.release.notes/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_79c774224c7b9290, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
}

func init() {
	proto.RegisterFile("github.com/infobloxopen/atlas-cli/github.release.notes/pkg/pb/service.proto", fileDescriptor_79c774224c7b9290)
}

var fileDescriptor_79c774224c7b9290 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0xbf, 0x4b, 0x03, 0x31,
	0x14, 0xb6, 0x8b, 0xc5, 0x2c, 0xc2, 0x0d, 0x52, 0x4e, 0x07, 0xe9, 0x24, 0xe8, 0xe5, 0x81, 0x8e,
	0x2e, 0xb5, 0x20, 0x1d, 0x04, 0x87, 0x1b, 0x3a, 0xb8, 0x25, 0xe7, 0x6b, 0x0c, 0xa6, 0x79, 0x8f,
	0x24, 0x3d, 0x7b, 0xff, 0xbd, 0xf4, 0x2e, 0x07, 0xc5, 0x8e, 0x6e, 0x79, 0xef, 0x7d, 0x7c, 0xbf,
	0x22, 0xde, 0x8c, 0x4d, 0x5f, 0x3b, 0x2d, 0x1b, 0xda, 0x82, 0xf5, 0x1b, 0xd2, 0x8e, 0xf6, 0xc4,
	0xe8, 0x41, 0x25, 0xa7, 0x62, 0xd5, 0x38, 0x0b, 0x19, 0x11, 0xd0, 0xa1, 0x8a, 0x28, 0x3d, 0x25,
	0x8c, 0xc0, 0xdf, 0x06, 0x58, 0x43, 0xc4, 0xd0, 0xda, 0x06, 0x25, 0x07, 0x4a, 0x54, 0x4c, 0xf3,
	0x58, 0x5e, 0x1b, 0x22, 0xe3, 0x10, 0xfa, 0xb5, 0xde, 0x6d, 0x00, 0xb7, 0x9c, 0xba, 0x01, 0x55,
	0xde, 0xe4, 0xa3, 0x62, 0x0b, 0xca, 0x7b, 0x4a, 0x2a, 0x59, 0xf2, 0x31, 0x5f, 0x5f, 0x8e, 0x0c,
	0xa1, 0x6f, 0xa9, 0xe3, 0x40, 0xfb, 0x6e, 0x60, 0x6a, 0x2a, 0x83, 0xbe, 0x6a, 0x95, 0xb3, 0x9f,
	0x2a, 0x21, 0x9c, 0x3c, 0x32, 0xc5, 0xc3, 0x11, 0x38, 0xfe, 0x28, 0x63, 0x30, 0x00, 0x71, 0x2f,
	0x72, 0x2a, 0x38, 0xbf, 0x17, 0x97, 0x6b, 0x0c, 0xd1, 0x92, 0xaf, 0x31, 0x32, 0xf9, 0x88, 0xc5,
	0x4c, 0x4c, 0xdb, 0x61, 0x35, 0x9b, 0xdc, 0x4e, 0xee, 0x2e, 0xea, 0x71, 0x7c, 0x5c, 0x8b, 0x62,
	0xd5, 0xfb, 0xab, 0x87, 0x36, 0xde, 0x0f, 0x65, 0x14, 0x0b, 0x21, 0x56, 0x98, 0x32, 0x4b, 0x71,
	0x25, 0x87, 0x80, 0x72, 0x4c, 0x2f, 0x5f, 0x0f, 0xe9, 0xcb, 0x99, 0x1c, 0xdb, 0xfa, 0xa3, 0x37,
	0x3f, 0x5b, 0x2e, 0x3f, 0x16, 0xff, 0xfa, 0x88, 0x67, 0xd6, 0xfa, 0xbc, 0xd7, 0x7b, 0xfa, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x00, 0x33, 0xed, 0xaa, 0xd3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GithubReleaseNotesClient is the client API for GithubReleaseNotes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GithubReleaseNotesClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type githubReleaseNotesClient struct {
	cc *grpc.ClientConn
}

func NewGithubReleaseNotesClient(cc *grpc.ClientConn) GithubReleaseNotesClient {
	return &githubReleaseNotesClient{cc}
}

func (c *githubReleaseNotesClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/service.GithubReleaseNotes/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GithubReleaseNotesServer is the server API for GithubReleaseNotes service.
type GithubReleaseNotesServer interface {
	GetVersion(context.Context, *empty.Empty) (*VersionResponse, error)
}

func RegisterGithubReleaseNotesServer(s *grpc.Server, srv GithubReleaseNotesServer) {
	s.RegisterService(&_GithubReleaseNotes_serviceDesc, srv)
}

func _GithubReleaseNotes_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GithubReleaseNotesServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.GithubReleaseNotes/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GithubReleaseNotesServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _GithubReleaseNotes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.GithubReleaseNotes",
	HandlerType: (*GithubReleaseNotesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _GithubReleaseNotes_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/infobloxopen/atlas-cli/github.release.notes/pkg/pb/service.proto",
}
