name: release-notes
on:
  push:
    tags: ['*']
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run release.notes image
        uses: infobloxopen/github.release.notes@7b259382ed223d3db21cb18d7d3e2089c1500a81
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: ${GITHUB_REF#refs/*/}
          github-user: ${{ github.actor }}
          github-repo: $GITHUB_REPOSITORY
