name: release-notes
on:
  push:
    tags: ['*']
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env        
        id: vars        
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}      
      - name: Run release.notes image
        uses: infobloxopen/github.release.notes@cb9419dd6598de67d310b0fd08bae26822d6a972
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: ${{ steps.vars.outputs.tag }}
          github-user: ${{ github.actor }}
          github-repo: ${{ github.repository }}
